
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const DETAILS_PRODUCT = "DETAILS_PRODUCT";
export const ADD_CONTENT = "ADD_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const GET_UPDATE_CONTENT = "GET_UPDATE_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
